version: '3.6'

services:
   postgresql:
      image: kartoza/postgis:9.6-2.4
      container_name: ${COMPOSE_PROJECT_NAME}-postgresql
      volumes:
      - type: bind
        source: ./postgresql_data
        target: /var/lib/postgresql
      ports:
        - "5432:5432"
      env_file:
        - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"
   geoserver:
      image: kartoza/geoserver:2.13.0
      container_name: ${COMPOSE_PROJECT_NAME}-geoserver
      volumes:
        - type: bind
        source: ./geoserver_data
        target: /opt/geoserver/data_dir
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      depends_on:
        postgresql:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   postgresql-dbbackups:
     image: kartoza/pg-backup:9.6
     container_name: ${COMPOSE_PROJECT_NAME}-postgresql-backups
     volumes:
     - type: bind
       source: ./postgresql_backups
       target: /backups
     env_file:
     - docker-env/db-backups.env
     restart: on-failure
     depends_on:
       postgresql:
         condition: service_healthy
         